name: Parent
on:
  pull_request:
    branches:
      - 'DEVELOP/**'
    paths:
      - '**-svc/**'
  push:
    branches:
      - main
jobs:
  parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Dispatch initiating repository event
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PAT_TOKEN }}" https://api.github.com/repos/github-actions-multirepo/child/dispatches -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'